services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "5678:5678"
    environment:
      - TZ=Europe/Paris
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=Europe/Paris
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    depends_on:
      - mcp
    networks:
      - n8n_data

  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: city-score-mcp
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - n8n_data

volumes:
  n8n_data:

networks:
  n8n_data:
